---
title: "Untitled"
author: "Tim Steinert"
date: "2024-10-02"
output: 
  html_document:
    theme: flatly
    toc: yes
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE# Hide code initially, can be unfolded
 
)
```

# Data loading

## Removal of duplicates 

```{r}

projection_fund=function(x1){
  norm=function(x){sum(x^2)^.5}
  if(norm(x1[4:6]-x1[1:3])>=norm(x1[7:9]-x1[1:3])){
    x_H_bar_1=x1[4:6]-x1[1:3]
    x_H_bar_2=x1[7:9]-x1[1:3]
    r1=norm(x_H_bar_1)
    r2=norm(x_H_bar_2)
  }else{
    x_H_bar_1=x1[7:9]-x1[1:3]
    x_H_bar_2=x1[4:6]-x1[1:3]
    r1=norm(x_H_bar_1)
    r2=norm(x_H_bar_2)
  }
  
  theta1=atan2(x_H_bar_1[1],x_H_bar_1[2])
  x_H_tilde_1=c(0,sin(theta1)*x_H_bar_1[1]+cos(theta1)*x_H_bar_1[2],x_H_bar_1[3])
  phi1=-atan2(x_H_tilde_1[3],x_H_tilde_1[2])
  
  psi_1=matrix(c(cos(theta1),-sin(theta1),0,sin(theta1),cos(theta1),0,0,0,1),
               nrow=3,byrow = 1)
  psi_2=matrix(c(1,0,0,0,cos(phi1),-sin(phi1),0,sin(phi1),cos(phi1)),
               nrow=3,byrow = 1)
  
  x_H_tilde_2=psi_2%*%psi_1%*%x_H_bar_2
  
  phi2=-atan2(x_H_tilde_2[3],x_H_tilde_2[1])
  psi_3=matrix(c(cos(phi2),0,-sin(phi2),0,1,0,sin(phi2),0,cos(phi2)),
               nrow=3,byrow = 1)
  
  A1=c(r1,(psi_3%*%x_H_tilde_2)[1],(psi_3%*%x_H_tilde_2)[2])
  return(A1)
}
X=as.matrix(original_struct[X_names])
Y=as.matrix(original_struct[Y_names])

A=t(apply(X,1,projection_fund))
#A=matrix(rnorm(3*3641,mean(A),sd(A)),ncol=3)


a=diag(1,nrow(A),nrow(A))
for(i in 1:nrow(A)){
  for(j in 1:nrow(A)){
    if(i!=j){a[i,j]=sum((A[i,]-A[j,])^2)^.5}
  }
}

### DUPLICATES CHECK
threshold=1e-10
duplicates=c()
for(i in 1:1261){
  ind=which(a[i,]<threshold)
  duplicates=c(duplicates,ind[ind>i])
}

```

## Data visualisation 

```{r}

dat=list(original_struct,rot_0,rot_1,rot_2,rot_3,
         rot_4,rot_5,rot_6,rot_7,rot_8,rot_9)

rot_ind=sample(10,1261,replace = TRUE)
swap_ind=sample(2,1261,replace = TRUE)


X=(t(sapply(1:1261,function(i){
  if(swap_ind[i]==1){
  as.matrix(dat[[rot_ind[i]]][X_names])[i,]
}else{
as.matrix(dat[[rot_ind[i]]][X_names])[i,c(1:3,7:9,4:6)]
}
}))+t(sapply(1:1261,function(i){
  a=runif(3,-2,2)
  rep(a,3)
})))[-duplicates,]


Y=t(sapply(1:1261,function(i){
  as.matrix(dat[[rot_ind[i]]][Y_names])[i,]
}))[-duplicates,]


X_O=X[,1:3];X_H1=X[,4:6];X_H2=X[,7:9]
osize=2.5;size=2.5
open3d(silent = TRUE)
plot3d(X_O,xlim=range(X_O[,1]),
       ylim=range(X_O[,2]),
       zlim=range(X_O[,3]),type='p',cex=.1,main="",col=2,
       
       xlab = "", ylab = "", zlab = "",size = osize)
#legend("topright",c(1,2,3,4),lty=1,col=1:4)
plot3d(X_H1,xlim=range(X_H1[,1]),
       ylim=range(X_H1[,2]),
       zlim=range(X_H1[,3]),type='p',cex=.1,main="Data",
       col="lightblue",add = 1,size = size)

plot3d(X_H2,xlim=range(X_H2[,1]),
       ylim=range(X_H2[,2]),
       zlim=range(X_H2[,3]),type='p',cex=.1,main="Data",
       col="blue",add = 1,size = size)



plot3d(Y,xlim=range(Y[,1]),
       ylim=range(Y[,2]),
       zlim=range(Y[,3]),type='p',cex=.1,main="Data",
       col="orange",add = 1,size = size)
rglwidget()
```
